log:
  home: "logs"
  file: "go-rss2webhook.log"
  color: true
  local: true

cron:
  enable: true
  tab: "0 * * * * ?"

store:
  # RSS订阅信息存储配置
  feed:
    # 将数据存储到 内存[memory] 文件系统[file] 配置文件[viper]
    type: "viper"
    # 文件系统配置
    file:
      # 文件存储路径
      path: "/tmp/GoRss2Webhook/data"
      # 文件名称
      name: "feed.json"
    # viper配置
    viper:
      path: "/tmp/GoRss2Webhook/data"
      name: "feed"
      type: "yaml"
  # RSS历史记录存储配置
  rss:
    type: "memory"
    # 文件系统配置
    file:
      # 文件存储父级目录，每一个RSS订阅一个文件夹，里面放的是每一次订阅的信息
      path: "/tmp/GoRss2Webhook/rss_store"
  # Webhook配置
  webhook:
    type: "viper"
    # 文件系统配置
    file:
      # 文件存储路径
      path: "/tmp/GoRss2Webhook/data"
      # 文件名称
      name: "webhook.json"
    # viper配置
    viper:
      path: "/tmp/GoRss2Webhook/data"
      name: "webhook"
      type: "yaml"